logging: 
  config: classpath:log4j2-production.yml
spring: 
  cloud: 
    stream: 
      kafka: 
        binder: 
          brokers: master1.bigdata,master2.bigdata,master3.bigdata
          defaultBrokerPort: 9872
          zkNodes: master1.bigdata,master2.bigdata,master3.bigdata
          defaultZkPort: 12181
  redis: 
    database: 0
    host: 10.104.237.66
    port: 6379
    password: "{cipher}AQBSQDWwxoE1MOTovH4bgd6HwPk3m0wMaN0Btc0Vc4Pl/K9NzPXOzl88+JcmnkZAGQYwJ1kLQW0RV41r7a0n33VmwBXXpwIM/3Z3zrERNChRJtAV6o92yjN9HaY2iaSk6fIBTUSbTWiDyLFyDcTQqLTmueA/ZSNWW4bXTQIscjkvfAyoxqOBFXa4nQ3DNYp1gz5nmw7fCQewnj19mENZKmEhy6Cqi9264EMEIFZmNAKpcyELjoDFvCZxGMtK1T1FhVwinb5Q1Eg8vdFZfHKAZzkBJfoySpSt8QPE0rToZxbrzeU3TOX4lOScb9HcXKtexy0nX440OJjEU+1ec6V2yUF3vTvj+TijfXEtWqBLyroc+aR2BG1lVX4nUMWI5yRYhow="
    jedis: 
      pool: 
        max-wait: -1
        max-idle: 20
        min-idle: 0
    timeout: 2000
management:
  security:
    enabled: false