spring:   
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.66.121.198:3306/monitoring?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: "{cipher}AQCNcB26tYGlE8fptFH/7NNkJYoNpxfUkdqsECR4bsT/LIKV++6AUPta1FEta1MWX2MZix+r/K1HKu3S27t6Wq/JibHoku6xb4wh1EbgKDxlx4QpjLuZOWng3RgrK7Wg8GOHBgLdbW47ASP1a/32DoLs3058YmGTGlmQomDuhprs/JDbSu6FO6/dHKbsQ+ySf7XOoFQ36QI99dYOQihSfw4MWuD9dfhZtyW+zSGn+VX0jB32aLPWVrd7Jk8XxISdpEEH2DtbZB1rVFH2wwu5nmZPy2cGLyrVDc+xlNQPQm/ADGEGHHscJ2RDQuSw1JTmOz4t2N8RzoUwePieIAVjznTgP0OXOofmgFd+9O9t1eo8jw4RV8Ide5LCqFNwbQoyXu4="
    password: "{cipher}AQAGiDDDTvTfuJiF9T5zs3OU8aOcIz+mpzfwRQsIuG8XopNxELGGPD6LhLnuX+Bq2gcovRw9j/4XoDjKhOCNpwa1kiItwqZfW01WXd8e+F66EXpIcfHpIt/pZZtfED1mcWNPWiXmZmIZQVIypvSa/5thidDepkMAlZTzLoqZXXMVa88o2cdUfMphHLXDVWZA1aFODKfn1AhCCvFMXNCbsgzM0BWb7ma4KQA3ku8ujv5M4OkyZc/h+anwOutnwtZYutZheqeNXIAjIT3p9WM7AIYMF0N8gdHuIsuQNqsj1RZ0tUPukNHYZOGnudpmVF/FnmqjGe6gSG4k55ueamyOvpda2RPxuiMx0bjwwHfkfGpyz0XNGiS+m/wkrMyPk6OLN9o="
    druid:
      initialSize: 10
      minIdle: 5
      maxActive: 100
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMills: 300000
      testOnBorrow: false
      testWhileIdle: true
      testOnReutrn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      useGlobalDataSourceStat: true
  #open-falcon的接口地址和登录的用户的账号和密码
falcon:
    user:
      name: "{cipher}AQB/ALCxuFr24u98W++I4qv/zoWGqjByyx3CQzrFAI52CAuwdPpC0TFIYnulVR8j194Gdr3sH5HIiCsHKH1DhV+Y9/85TImll2kQJ6UEwaWUB4PQbuWHuOxEA9BAhKvsWuGhsDaMdM4+WRFucrLr7i0jH2D5PxUcrG4rQHg5HAeXU0YuKgcrkYAwBtxXaveF+lkx81mBz47OHys5kuOpXhuVMYK03l2zH9dlNZ9JQq50Qru3yDkgK3KmagG3Am3DsQrNfZckmL7c3xHZ1CNbrKHkC9NG1E0klTha6Ykg1zmMraefxFdntnzmkMDLS+hLWV1y40aHoYT4th2oRnk4ai/wI879l3ByVF8vM6XjiIbiKZtvJ+8tDaU99meiYnEJ8bM=" #open-falcon账户名字，
      sig: "{cipher}AQBeVc4En/WTWLVCEetrSF1djvD9wEpGqna1yETosQrXu0TqT/jZ23XqEa07iXk3GO7YMqgWC8BF0IlPapizzHz+MbJtBLMkO27437FZ5cWprl5jH55BPcxEFYbYYZ//R2EoEaETjfjh3hc1z2mT/O1Z0j/xUOJFJp/ouPIXB7lhsKfurSu56CF+RrqRn+ppdEHmXZ7SHnmlxmypYjnY16+ky8/+t9xU6ZZ3YXpWYUNkf9A2HHXozdmC8U893vTlNfsi4VC4qU3b7MogmHSykIn+qcv4KgATwZe7fgTqvbaijO3zouIl5mi1kaCb9q5eFNIY8gnzQ3+WYabscDT16sJOIqNvxjkg4EfvCmjVQejtkshs9JINRKGe3Ydy0Epw2SF/RWe0U2TBCjuGqITEvpU+KvOCF1HfPw5XNfLT0pCZwQ=="
    pushUrl: http://10.104.237.66:1988/v1/push #推送自定义消息
    api: http://10.104.237.66:18080/api/v1/
    query:
      history: graph/history #查询历史消息