server: 
  protocol: org.apache.coyote.http11.Http11NioProtocol
logging:
  config: classpath:log4j2-development.yml
spring:
  cloud:
    stream: 
      kafka: 
        binder: 
          brokers: master1.bigdata,master2.bigdata,master3.bigdata
          defaultBrokerPort: 9872
          zkNodes: master1.bigdata,master2.bigdata,master3.bigdata
          defaultZkPort: 12181
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  cache:
    type: REDIS
  redis:
    database: 0
    host: 10.104.237.66
    port: 6379
    password: "{cipher}AQBSQDWwxoE1MOTovH4bgd6HwPk3m0wMaN0Btc0Vc4Pl/K9NzPXOzl88+JcmnkZAGQYwJ1kLQW0RV41r7a0n33VmwBXXpwIM/3Z3zrERNChRJtAV6o92yjN9HaY2iaSk6fIBTUSbTWiDyLFyDcTQqLTmueA/ZSNWW4bXTQIscjkvfAyoxqOBFXa4nQ3DNYp1gz5nmw7fCQewnj19mENZKmEhy6Cqi9264EMEIFZmNAKpcyELjoDFvCZxGMtK1T1FhVwinb5Q1Eg8vdFZfHKAZzkBJfoySpSt8QPE0rToZxbrzeU3TOX4lOScb9HcXKtexy0nX440OJjEU+1ec6V2yUF3vTvj+TijfXEtWqBLyroc+aR2BG1lVX4nUMWI5yRYhow="
    jedis: 
      pool: 
        max-wait: -1
        max-idle: 20
        min-idle: 0
    timeout: 2000
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.66.121.198:3306/monitoring?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
    username: "{cipher}AQCNcB26tYGlE8fptFH/7NNkJYoNpxfUkdqsECR4bsT/LIKV++6AUPta1FEta1MWX2MZix+r/K1HKu3S27t6Wq/JibHoku6xb4wh1EbgKDxlx4QpjLuZOWng3RgrK7Wg8GOHBgLdbW47ASP1a/32DoLs3058YmGTGlmQomDuhprs/JDbSu6FO6/dHKbsQ+ySf7XOoFQ36QI99dYOQihSfw4MWuD9dfhZtyW+zSGn+VX0jB32aLPWVrd7Jk8XxISdpEEH2DtbZB1rVFH2wwu5nmZPy2cGLyrVDc+xlNQPQm/ADGEGHHscJ2RDQuSw1JTmOz4t2N8RzoUwePieIAVjznTgP0OXOofmgFd+9O9t1eo8jw4RV8Ide5LCqFNwbQoyXu4="
    password: "{cipher}AQAGiDDDTvTfuJiF9T5zs3OU8aOcIz+mpzfwRQsIuG8XopNxELGGPD6LhLnuX+Bq2gcovRw9j/4XoDjKhOCNpwa1kiItwqZfW01WXd8e+F66EXpIcfHpIt/pZZtfED1mcWNPWiXmZmIZQVIypvSa/5thidDepkMAlZTzLoqZXXMVa88o2cdUfMphHLXDVWZA1aFODKfn1AhCCvFMXNCbsgzM0BWb7ma4KQA3ku8ujv5M4OkyZc/h+anwOutnwtZYutZheqeNXIAjIT3p9WM7AIYMF0N8gdHuIsuQNqsj1RZ0tUPukNHYZOGnudpmVF/FnmqjGe6gSG4k55ueamyOvpda2RPxuiMx0bjwwHfkfGpyz0XNGiS+m/wkrMyPk6OLN9o="
    druid:
      initialSize: 10
      minIdle: 5
      maxActive: 100
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMills: 300000
      testOnBorrow: false
      testWhileIdle: true
      testOnReutrn: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      filters: stat,wall,log4j
      useGlobalDataSourceStat: true
  #open-falcon的接口地址和登录的用户的账号和密码
falcon:
    user:
      name: root #open-falcon账户名字，
      sig: 81d05084b57111e7bb445254009494f2
    pushUrl: http://111.230.166.38:1988/v1/push #推送自定义消息
    api: http://111.230.166.38:18080/api/v1/
    query:
      history: graph/history #查询历史消息